#!/usr/bin/python3

from fw_victron.dbus_definitions import *
from fw_victron.ve_parsers import *


def dev_type_to_code(device_type) -> str:
    """ make given string lower case and replace whitespaces with '_' """
    return device_type.lower().replace(' ', '_')


# Given an PID, this object returns all his info and meta-data
PID = {
    "0x203": {"model": "BMV-700", "type": DEV_TYPE_BMV,
              "dbus_iface": DEV_IFACE_BMV, "dbus_desc": None},
    "0x204": {"model": "BMV-702", "type": DEV_TYPE_BMV,
              "dbus_iface": DEV_IFACE_BMV, "dbus_desc": None},
    "0x205": {"model": "BMV-700H", "type": DEV_TYPE_BMV,
              "dbus_iface": DEV_IFACE_BMV, "dbus_desc": None},
    "0xA042": {"model": "BlueSolar MPPT 75|15", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA043": {"model": "BlueSolar MPPT 100|15", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA046": {"model": "BlueSolar MPPT 150|70", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA047": {"model": "BlueSolar MPPT 150|100 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA049": {"model": "BlueSolar MPPT 100|50 rev2 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA04A": {"model": "BlueSolar MPPT 100|30 rev2 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA04B": {"model": "BlueSolar MPPT 150|35 rev2 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA04C": {"model": "BlueSolar MPPT 75|10 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA04D": {"model": "BlueSolar MPPT 150|45 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA04E": {"model": "BlueSolar MPPT 150|60 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA04F": {"model": "BlueSolar MPPT 150|85 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA050": {"model": "SmartSolar MPPT 250|100 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA053": {"model": "SmartSolar MPPT 75|15 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA054": {"model": "SmartSolar MPPT 75|10 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA055": {"model": "SmartSolar MPPT 100|15 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA056": {"model": "SmartSolar MPPT 100|30 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA057": {"model": "SmartSolar MPPT 100|50 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA058": {"model": "SmartSolar MPPT 150|35 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA059": {"model": "SmartSolar MPPT 150|100 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA05A": {"model": "SmartSolar MPPT 150|85 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA05B": {"model": "SmartSolar MPPT 250|70 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA05C": {"model": "SmartSolar MPPT 250|85 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA05D": {"model": "SmartSolar MPPT 250|60 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA05E": {"model": "SmartSolar MPPT 250|45 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA05F": {"model": "SmartSolar MPPT 100|20 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA060": {"model": "SmartSolar MPPT 100|20 48V ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA061": {"model": "SmartSolar MPPT 150|45 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA062": {"model": "SmartSolar MPPT 150|60 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA063": {"model": "SmartSolar MPPT 150|70 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA064": {"model": "SmartSolar MPPT 250|85 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA065": {"model": "SmartSolar MPPT 250|100 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA066": {"model": "BlueSolar MPPT 100|20 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA067": {"model": "BlueSolar MPPT 100|20 48V ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA068": {"model": "SmartSolar MPPT 250|60 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA069": {"model": "SmartSolar MPPT 250|70 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA06A": {"model": "SmartSolar MPPT 150|45 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA06B": {"model": "SmartSolar MPPT 150|60 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA06C": {"model": "SmartSolar MPPT 150|70 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA06D": {"model": "SmartSolar MPPT 150|85 rev3 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA06E": {"model": "SmartSolar MPPT 150|100 rev3 ", "type": DEV_TYPE_SmartSolar_MPPT,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA06F": {"model": "BlueSolar MPPT 150|45 rev2 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA070": {"model": "BlueSolar MPPT 150|60 rev2 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA071": {"model": "BlueSolar MPPT 150|70 rev2 ", "type": DEV_TYPE_BlueSolar_MPPT,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT, "dbus_desc": None},
    "0xA102": {"model": "SmartSolar MPPT VE.Can 150/70 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA103": {"model": "SmartSolar MPPT VE.Can 150/45 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA104": {"model": "SmartSolar MPPT VE.Can 150/60 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA105": {"model": "SmartSolar MPPT VE.Can 150/85 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA106": {"model": "SmartSolar MPPT VE.Can 150/100 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA107": {"model": "SmartSolar MPPT VE.Can 250/45 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA108": {"model": "SmartSolar MPPT VE.Can 250/60 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA109": {"model": "SmartSolar MPPT VE.Can 250/70 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA10A": {"model": "SmartSolar MPPT VE.Can 250/85 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA10B": {"model": "SmartSolar MPPT VE.Can 250/100 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA10C": {"model": "SmartSolar MPPT VE.Can 150/70 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA10D": {"model": "SmartSolar MPPT VE.Can 150/85 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA10E": {"model": "SmartSolar MPPT VE.Can 150/100 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA10F": {"model": "BlueSolar MPPT VE.Can 150/100 ", "type": DEV_TYPE_BlueSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT_VECan, "dbus_desc": None},
    "0xA112": {"model": "BlueSolar MPPT VE.Can 250/70 ", "type": DEV_TYPE_BlueSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT_VECan, "dbus_desc": None},
    "0xA113": {"model": "BlueSolar MPPT VE.Can 250/100 ", "type": DEV_TYPE_BlueSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_BlueSolar_MPPT_VECan, "dbus_desc": None},
    "0xA114": {"model": "SmartSolar MPPT VE.Can 250/70 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA115": {"model": "SmartSolar MPPT VE.Can 250/100 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA116": {"model": "SmartSolar MPPT VE.Can 250/85 rev2 ", "type": DEV_TYPE_SmartSolar_MPPT_VECan,
               "dbus_iface": DEV_IFACE_SmartSolar_MPPT_VECan, "dbus_desc": DEV_DBUS_DESC_SmartSolar_MPPT},
    "0xA231": {"model": "Phoenix Inverter 12V 250VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA232": {"model": "Phoenix Inverter 24V 250VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA234": {"model": "Phoenix Inverter 48V 250VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA239": {"model": "Phoenix Inverter 12V 250VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA23A": {"model": "Phoenix Inverter 24V 250VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA23C": {"model": "Phoenix Inverter 48V 250VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA241": {"model": "Phoenix Inverter 12V 375VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA242": {"model": "Phoenix Inverter 24V 375VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA244": {"model": "Phoenix Inverter 48V 375VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA249": {"model": "Phoenix Inverter 12V 375VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA24A": {"model": "Phoenix Inverter 24V 375VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA24C": {"model": "Phoenix Inverter 48V 375VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA251": {"model": "Phoenix Inverter 12V 500VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA252": {"model": "Phoenix Inverter 24V 500VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA254": {"model": "Phoenix Inverter 48V 500VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA259": {"model": "Phoenix Inverter 12V 500VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA25A": {"model": "Phoenix Inverter 24V 500VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA25C": {"model": "Phoenix Inverter 48V 500VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA261": {"model": "Phoenix Inverter 12V 800VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA262": {"model": "Phoenix Inverter 24V 800VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA264": {"model": "Phoenix Inverter 48V 800VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA269": {"model": "Phoenix Inverter 12V 800VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA26A": {"model": "Phoenix Inverter 24V 800VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA26C": {"model": "Phoenix Inverter 48V 800VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA271": {"model": "Phoenix Inverter 12V 1200VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA272": {"model": "Phoenix Inverter 24V 1200VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA274": {"model": "Phoenix Inverter 48V 1200VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA279": {"model": "Phoenix Inverter 12V 1200VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA27A": {"model": "Phoenix Inverter 24V 1200VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA27C": {"model": "Phoenix Inverter 48V 1200VA 120V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA281": {"model": "Phoenix Inverter 12V 1600VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA282": {"model": "Phoenix Inverter 24V 1600VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA284": {"model": "Phoenix Inverter 48V 1600VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA291": {"model": "Phoenix Inverter 12V 2000VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA292": {"model": "Phoenix Inverter 24V 2000VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA294": {"model": "Phoenix Inverter 48V 2000VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA2A1": {"model": "Phoenix Inverter 12V 3000VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA2A2": {"model": "Phoenix Inverter 24V 3000VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA2A4": {"model": "Phoenix Inverter 48V 3000VA 230V ", "type": DEV_TYPE_Phoenix_Inverter,
               "dbus_iface": DEV_IFACE_Phoenix_Inverter, "dbus_desc": None},
    "0xA340": {"model": "Phoenix Smart IP43 Charger 12|50 (1+1) ", "type": DEV_TYPE_Phoenix_Smart_IP43_Charger,
               "dbus_iface": DEV_IFACE_Phoenix_Smart_IP43_Charger, "dbus_desc": None},
    "0xA341": {"model": "Phoenix Smart IP43 Charger 12|50 (3) ", "type": DEV_TYPE_Phoenix_Smart_IP43_Charger,
               "dbus_iface": DEV_IFACE_Phoenix_Smart_IP43_Charger, "dbus_desc": None},
    "0xA342": {"model": "Phoenix Smart IP43 Charger 24|25 (1+1) ", "type": DEV_TYPE_Phoenix_Smart_IP43_Charger,
               "dbus_iface": DEV_IFACE_Phoenix_Smart_IP43_Charger, "dbus_desc": None},
    "0xA343": {"model": "Phoenix Smart IP43 Charger 24|25 (3) ", "type": DEV_TYPE_Phoenix_Smart_IP43_Charger,
               "dbus_iface": DEV_IFACE_Phoenix_Smart_IP43_Charger, "dbus_desc": None},
    "0xA344": {"model": "Phoenix Smart IP43 Charger 12|30 (1+1) ", "type": DEV_TYPE_Phoenix_Smart_IP43_Charger,
               "dbus_iface": DEV_IFACE_Phoenix_Smart_IP43_Charger, "dbus_desc": None},
    "0xA345": {"model": "Phoenix Smart IP43 Charger 12|30 (3) ", "type": DEV_TYPE_Phoenix_Smart_IP43_Charger,
               "dbus_iface": DEV_IFACE_Phoenix_Smart_IP43_Charger, "dbus_desc": None},
    "0xA346": {"model": "Phoenix Smart IP43 Charger 24|16 (1+1) ", "type": DEV_TYPE_Phoenix_Smart_IP43_Charger,
               "dbus_iface": DEV_IFACE_Phoenix_Smart_IP43_Charger, "dbus_desc": None},
    "0xA347": {"model": "Phoenix Smart IP43 Charger 24|16 (3) ", "type": DEV_TYPE_Phoenix_Smart_IP43_Charger,
               "dbus_iface": DEV_IFACE_Phoenix_Smart_IP43_Charger, "dbus_desc": None},
    "0xA389": {"model": "SmartShunt 500A/50mV", "type": DEV_TYPE_SmartShunt,
               "dbus_iface": DEV_IFACE_SmartShunt, "dbus_desc": None},
}

PROPS_CODES = {
    "V": {"name": "battery_voltage", "desc": "Main or channel 1 (battery) voltage",
          "parser": props_parser_float},
    "V2": {"name": "battery_voltage_ch2", "desc": "Channel 2 (battery) voltage",
           "parser": props_parser_float},
    "V3": {"name": "battery_voltage_ch3", "desc": "Channel 3 (battery) voltage",
           "parser": props_parser_float},
    "VS": {"name": "battery_voltage_aux", "desc": "Auxiliary (starter) voltage",
           "parser": props_parser_float},
    "VM": {"name": "mid_point_voltage", "desc": "Mid-point voltage of the battery bank",
           "parser": props_parser_float},
    "DM": {"name": "mid_point_deviation", "desc": "Mid-point deviation of the battery bank",
           "parser": props_parser_float},
    "VPV": {"name": "panel_voltage", "desc": "Panel voltage",
            "parser": props_parser_float},
    "PPV": {"name": "panel_power", "desc": "Panel power",
            "parser": props_parser_float},
    "I": {"name": "battery_current", "desc": "Main or channel 1 battery current",
          "parser": props_parser_float},
    "I2": {"name": "battery_current_ch2", "desc": "Channel 2 battery current",
           "parser": props_parser_float},
    "I3": {"name": "battery_current_ch3", "desc": "Channel 3 battery current",
           "parser": props_parser_float},
    "IL": {"name": "load_current", "desc": "Load current",
           "parser": props_parser_float},
    "LOAD": {"name": "load_state", "desc": "Load output state (ON/OFF)",
             "parser": props_parser_on_off},
    "T": {"name": "battery_temperature", "desc": "Battery temperature",
          "parser": props_parser_float},
    "P": {"name": "instantaneous_power", "desc": "Instantaneous power",
          "parser": props_parser_float},
    "CE": {"name": "consumed_amp_hours", "desc": "Consumed Amp Hours",
           "parser": props_parser_float},
    "SOC": {"name": "state_of_charge", "desc": "State of charge",
            "parser": props_parser_float},
    "TTG": {"name": "time_to_go", "desc": "Time to go",
            "parser": props_parser_int},
    "Alarm": {"name": "alarm_condition", "desc": "Alarm condition active",
              "parser": props_parser_on_off},
    "Relay": {"name": "relay_state", "desc": "Relay state",
              "parser": props_parser_on_off},
    "AR": {"name": "alarm_reason", "desc": "Alarm reason",
           "parser": props_parser_alarm_or_warning_reason},
    "OR": {"name": "off_reason", "desc": "Off reason",
           "parser": props_parser_off_reason},
    "H1": {"name": "depth_deepest_discharge", "desc": "Depth of the deepest discharge",
           "parser": props_parser_float},
    "H2": {"name": "depth_last_discharge", "desc": "Depth of the last discharge",
           "parser": props_parser_float},
    "H3": {"name": "depth_average_discharge", "desc": "Depth of the average discharge",
           "parser": props_parser_float},
    "H4": {"name": "number_charge_cycles", "desc": "Number of charge cycles",
           "parser": props_parser_int},
    "H5": {"name": "number_full_discharges", "desc": "Number of full discharges",
           "parser": props_parser_int},
    "H6": {"name": "cumulative_mp_drawn", "desc": "Cumulative Amp Hours drawn",
           "parser": props_parser_float},
    "H7": {"name": "min_battery_voltage", "desc": "Minimum main (battery) voltage",
           "parser": props_parser_float},
    "H8": {"name": "max_battery_voltage", "desc": "Maximum main (battery) voltage",
           "parser": props_parser_float},
    "H9": {"name": "seconds_since_last_full_charge", "desc": "Number of seconds since last full charge",
           "parser": props_parser_int},
    "H10": {"name": "number_automatic_synchronizations", "desc": "Number of automatic synchronizations",
            "parser": props_parser_int},
    "H11": {"name": "number_low_voltage_alarms", "desc": "Number of low main voltage alarms",
            "parser": props_parser_int},
    "H12": {"name": "number_high_voltage_alarms", "desc": "Number of high main voltage alarms",
            "parser": props_parser_int},
    "H13": {"name": "number_low_voltage_alarms_aux", "desc": "Number of low auxiliary voltage alarms",
            "parser": props_parser_int},
    "H14": {"name": "number_high_voltage_alarms_aux", "desc": "Number of high auxiliary voltage alarms",
            "parser": props_parser_int},
    "H15": {"name": "min_battery_voltage_aux", "desc": "Minimum auxiliary (battery) voltage",
            "parser": props_parser_float},
    "H16": {"name": "max_battery_voltage_aux", "desc": "Maximum auxiliary (battery) voltage",
            "parser": props_parser_float},
    "H17": {"name": "discharged_energy",
            "desc": "Amount of discharged energy (BMV) / Amount of produced energy (DC monitor)",
            "parser": props_parser_float},
    "H18": {"name": "charged_energy", "desc": "Amount of charged energy (BMV) / Amount of consumed energy (DC monitor)",
            "parser": props_parser_float},
    "H19": {"name": "yield_total", "desc": "Yield total (user resettable counter)",
            "parser": props_parser_float},
    "H20": {"name": "yield_today", "desc": "Yield today",
            "parser": props_parser_float},
    "H21": {"name": "max_power_today", "desc": "Maximum power today",
            "parser": props_parser_float},
    "H22": {"name": "yield_yesterday", "desc": "Yield yesterday",
            "parser": props_parser_float},
    "H23": {"name": "max_power_yesterday", "desc": "Maximum power yesterday",
            "parser": props_parser_float},
    "ERR": {"name": "error_code", "desc": "Error code",
            "parser": props_parser_error_code},
    "CS": {"name": "state_operation", "desc": "State of operation",
           "parser": props_parser_state_operation},
    "BMV": {"name": "model_description", "desc": "Model description (deprecated)",
            "parser": props_parser_model_description},
    "FW": {"name": "firmware_version", "desc": "Firmware version (16 bit)",
           "parser": props_parser_fw16},
    "FWE": {"name": "firmware_version", "desc": "Firmware version (24 bit)",
            "parser": props_parser_fw24},
    "PID": {"name": "product_id", "desc": "Product ID",
            "parser": props_parser_none},
    "SER#": {"name": "serial_number", "desc": "Product Serial number",
             "parser": props_parser_none},
    "HSDS": {"name": "day_sequence_number", "desc": "Day sequence number (0..364)",
             "parser": props_parser_int},
    "MODE": {"name": "device_mode", "desc": "Device mode",
             "parser": props_parser_mode},
    "AC_OUT_V": {"name": "ac_output_voltage", "desc": "AC output voltage",
                 "parser": props_parser_float},
    "AC_OUT_I": {"name": "ac_output_current", "desc": "AC output current",
                 "parser": props_parser_float},
    "AC_OUT_S": {"name": "ac_output_apparent_power", "desc": "AC output apparent power",
                 "parser": props_parser_float},
    "WARN": {"name": "warning_reason", "desc": "Warning reason",
             "parser": props_parser_alarm_or_warning_reason},
    "MPPT": {"name": "tracker_operation_mode", "desc": "Tracker operation mode (MPPT)",
             "parser": props_parser_mode_mppt},
    "MON": {"name": "dc_monitor_mode", "desc": "DC monitor mode",
            "parser": props_parser_mode_monitor},
    "DC_IN_V": {"name": "dc_input_voltage", "desc": "DC input voltage",
                "parser": props_parser_float},
    "DC_IN_I": {"name": "dc_input_current", "desc": "DC input current",
                "parser": props_parser_float},
    "DC_IN_P": {"name": "dc_input_power", "desc": "DC input power",
                "parser": props_parser_float},
}
